version: "3.8"
services:
  dev_db:
    image: postgres:15.1-alpine3.17
    container_name: postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network

networks:
  postgres-network:
