version: "3.8"
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      profile: prod
      db_pass: pass
  db:
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: nuxt3go
      POSTGRES_DB: nuxt3go
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql