version: "3.8"
services:
  dev_db:
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_PASSWORD: passpwdX6754
      POSTGRES_USER: nuxt3go
      POSTGRES_DB: nuxt3go
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
